apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-monitor
#  namespace: traefik
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: maesh
      service: traefik-mesh
  endpoints:
    - port: api
  targetLabels:
    # prometheus converts . to _
    - service.name