# this needs prometheus installed for custom resource definition
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: static-web-monitor
  namespace: ${namespace}
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      service: static-web-frontend
  endpoints:
    - port: http
