apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ${secretName} # name of the k8s external secret and the k8s secret
  namespace: ${namespace}
spec:
  backendType: gcpSecretsManager
  projectId: ${projectID}
  data:
    - key: ${secretName} # name of the GCP secret
      name: "token.txt"
      version: latest # version of the GCP secret
      property: value # name of the field in the GCP secret