# apiVersion: getambassador.io/v2
# kind: Host
# metadata:
#   name: pepper-poker.wetsnow.com
#   namespace: ambassador
# spec:
#   acmeProvider:
#     email: dant@wetsnow.com
#   requestPolicy:
#     insecure:
#       action: Reject
#   hostname: pepper-poker.wetsnow.com
#   tlsSecret:
#     name: pepper-poker.wetsnow.com
# ---
# apiVersion: getambassador.io/v2
# kind: TLSContext
# metadata:
#   name: pepper-poker.wetsnow.com-context # for the host above
#   namespace: ambassador
# spec:
#   hosts:
#     - "pepper-poker.wetsnow.com"
#   secret: pepper-poker.wetsnow.com
#   alpn_protocols: h2,http/1.1 # required for C# grpc client
# ---
# apiVersion: getambassador.io/v2
# kind: Host
# metadata:
#   name: pepper-poker-grpc.wetsnow.com
#   namespace: ambassador
# spec:
#   acmeProvider:
#     email: dant@wetsnow.com
#   requestPolicy:
#     insecure:
#       action: Reject
#   hostname: pepper-poker-grpc.wetsnow.com
#   tlsSecret:
#     name: pepper-poker-grpc.wetsnow.com
# ---
# apiVersion: getambassador.io/v2
# kind: TLSContext
# metadata:
#   name: pepper-poker-grpc.wetsnow.com-context # for the host above
#   namespace: ambassador
# spec:
#   hosts:
#     - "pepper-poker-grpc.wetsnow.com"
#   secret: pepper-poker-grpc.wetsnow.com
#   alpn_protocols: h2,http/1.1 # required for C# grpc client
# ---
# apiVersion: getambassador.io/v2
# kind: Host
# metadata:
#   name: grafana.wetsnow.com
#   namespace: ambassador
# spec:
#   acmeProvider:
#     email: dant@wetsnow.com
#   hostname: grafana.wetsnow.com
#   tlsSecret:
#     name: grafana.wetsnow.com
# ---
# apiVersion: getambassador.io/v2
# kind: TLSContext
# metadata:
#   name: grafana.wetsnow.com-context # for the host above
#   namespace: ambassador
# spec:
#   hosts:
#     - "grafana.wetsnow.com"
#   secret: grafana.wetsnow.com
#   alpn_protocols: h2,http/1.1 # required for C# grpc client
# ---
# apiVersion: getambassador.io/v2
# kind: Host
# metadata:
#   name: login.wetsnow.com
#   namespace: ambassador
# spec:
#   acmeProvider:
#     email: dant@wetsnow.com
#   hostname: login.wetsnow.com
#   tlsSecret:
#     name: login.wetsnow.com
# ---
# apiVersion: getambassador.io/v2
# kind: TLSContext
# metadata:
#   name: login.wetsnow.com-context # for the host above
#   namespace: ambassador
# spec:
#   hosts:
#     - "login.wetsnow.com"
#   secret: login.wetsnow.com
#   alpn_protocols: h2,http/1.1 # required for C# grpc client
# ---
# apiVersion: getambassador.io/v2
# kind: Host
# metadata:
#   name: www.wetsnow.com
#   namespace: ambassador
# spec:
#   acmeProvider:
#     email: dant@wetsnow.com
#   requestPolicy:
#     insecure:
#       action: Redirect
#   hostname: www.wetsnow.com
#   tlsSecret:
#     name: www.wetsnow.com
# ---
# apiVersion: getambassador.io/v2
# kind: TLSContext
# metadata:
#   name: www.wetsnow.com-context # for the host above
#   namespace: ambassador
# spec:
#   hosts:
#     - "www.wetsnow.com"
#   secret: www.wetsnow.com
#   alpn_protocols: h2,http/1.1 # required for C# grpc client
# ---
# apiVersion: getambassador.io/v2
# kind: Host
# metadata:
#   name: wetsnow.com
#   namespace: ambassador
# spec:
#   acmeProvider:
#     email: dant@wetsnow.com
#   requestPolicy:
#     insecure:
#       action: Redirect
#   hostname: wetsnow.com
#   tlsSecret:
#     name: wetsnow.com
# ---
# apiVersion: getambassador.io/v2
# kind: Host
# metadata:
#   name: www.dusselskolk.com
#   namespace: ambassador
# spec:
#   acmeProvider:
#     email: dant@wetsnow.com
#   requestPolicy:
#     insecure:
#       action: Redirect
#   hostname: www.dusselskolk.com
#   tlsSecret:
#     name: www.dusselskolk.com
# ---
# apiVersion: getambassador.io/v2
# kind: TLSContext
# metadata:
#   name: www.dusselskolk.com-context # for the host above
#   namespace: ambassador
# spec:
#   hosts:
#     - "www.dusselskolk.com"
#   secret: www.dusselskolk.com
#   alpn_protocols: h2,http/1.1 # required for C# grpc client
# ---
# apiVersion: getambassador.io/v2
# kind: Host
# metadata:
#   name: dusselskolk.com
#   namespace: ambassador
# spec:
#   acmeProvider:
#     email: dant@wetsnow.com
#   requestPolicy:
#     insecure:
#       action: Redirect
#   hostname: dusselskolk.com
#   tlsSecret:
#     name: dusselskolk.com
# ---
# apiVersion: getambassador.io/v2
# kind: Host
# metadata:
#   name: prometheus.wetsnow.com
#   namespace: ambassador
# spec:
#   acmeProvider:
#     email: dant@wetsnow.com
#   hostname: prometheus.wetsnow.com
#   tlsSecret:
#     name: prometheus.wetsnow.com
# ---
# apiVersion: getambassador.io/v2
# kind: Host
# metadata:
#   name: pgadmin.wetsnow.com
#   namespace: ambassador
# spec:
#   acmeProvider:
#     email: dant@wetsnow.com
#   hostname: pgadmin.wetsnow.com
#   tlsSecret:
#     name: pgadmin.wetsnow.com
# ---
# apiVersion: getambassador.io/v2
# kind: Host
# metadata:
#   name: ambassador-admin.wetsnow.com
#   namespace: ambassador
# spec:
# acmeProvider:
#   email: dant@wetsnow.com
# hostname: ambassador-admin.wetsnow.com
# tlsSecret:
#   name: ambassador-admin.wetsnow.com
# ---
# apiVersion: getambassador.io/v2
# kind: Host
# metadata:
#   name: kafka-ui.wetsnow.com
#   namespace: ambassador
# spec:
#   acmeProvider:
#     email: dant@wetsnow.com
#   hostname: kafka-ui.wetsnow.com
#   tlsSecret:
#     name: kafka-ui.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: l7-redirect
  namespace: ambassador
spec:
  # hostname: www.wetsnow.com
  # TLS happens at the LB, so disable it here.
  acmeProvider:
    authority: none
  # The default insecure action is Redirect, which is fine.
