apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
  namespace: ambassador
spec:
  config:
    # use_proxy_proto: true
    xff_num_trusted_hops: 1
    envoy_log_type: json
    diagnostics:
      enabled: true
