---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: l7-redirect
  namespace: ambassador
spec:
  hostname: "*.com"
  # TLS happens at the LB, so disable it here.
  acmeProvider:
    authority: none
  # The default insecure action is Redirect, which is fine.
  # https://www.getambassador.io/docs/edge-stack/latest/topics/running/tls/cleartext-redirection/#http---https-redirection
  requestPolicy:
    insecure:
      action: Redirect
  mappingSelector:
    matchLabels:
      host: default
