---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: grafana
  namespace: ambassador
spec:
  prefix: /
  allow_upgrade:
    - websocket
  host: grafana.wetsnow.com
  resolver: endpoint
  timeout_ms: 80000 # some dashboards load slow?
  service: grafana0.monitoring:80
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: wetsnow.com
  namespace: ambassador
  labels:
    host: default
spec:
  prefix: /
  host: wetsnow.com
  resolver: endpoint
  timeout_ms: 20000 # /quote is slow
  service: static-web-frontend.web:8080
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: www.wetsnow.com
  namespace: ambassador
  labels:
    host: default
spec:
  prefix: /
  host: www.wetsnow.com
  resolver: endpoint
  timeout_ms: 20000 # /quote is slow
  service: static-web-frontend.web:8080
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: www.dusselskolk.com
  namespace: ambassador
  labels:
    host: default
spec:
  prefix: /
  host: www.dusselskolk.com
  resolver: endpoint
  service: static-web-frontend.web:8080
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: dusselskolk.com
  namespace: ambassador
  labels:
    host: default
spec:
  prefix: /
  host: dusselskolk.com
  resolver: endpoint
  service: static-web-frontend.web:8080
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: "404-fallback"
  namespace: ambassador
spec:
  prefix: "/"
  rewrite: "/404/" # This must not map to any existing prefix!
  service: localhost:8500
