---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: keycloak-pgadmin-filter
  namespace: ambassador
spec:
  OAuth2:
    authorizationURL: https://login.wetsnow.com/auth/realms/wetsnow
    clientID: default.wetsnow.com
    secretName: default-keycloak-secret
    # These are simply authorized_callbacks!
    protectedOrigins:
      - origin: https://pgadmin.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: keycloak-kowl-filter
  namespace: ambassador
spec:
  OAuth2:
    authorizationURL: https://login.wetsnow.com/auth/realms/wetsnow
    clientID: default.wetsnow.com
    secretName: default-keycloak-secret
    # These are simply authorized_callbacks!
    protectedOrigins:
      - origin: https://kafka-ui.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: keycloak-prometheus-filter
  namespace: ambassador
spec:
  OAuth2:
    authorizationURL: https://login.wetsnow.com/auth/realms/wetsnow
    clientID: default.wetsnow.com
    secretName: default-keycloak-secret
    # These are simply authorized_callbacks!
    protectedOrigins:
      - origin: https://prometheus.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: keycloak-pepper-poker-filter
  namespace: ambassador
spec:
  OAuth2:
    authorizationURL: https://login.wetsnow.com/auth/realms/wetsnow
    clientID: pepper-poker.wetsnow.com
    secretName: pepper-poker-keycloak-secret
    # These are simply authorized_callbacks!
    protectedOrigins:
      - origin: https://pepper-poker.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: keycloak-wetsnow-com-filter
  namespace: ambassador
spec:
  OAuth2:
    authorizationURL: https://login.wetsnow.com/auth/realms/wetsnow
    injectRequestHeaders:
      - name: x-id-token
        value: "{{ .token.Claims }}"
    clientID: default.wetsnow.com
    secretName: default-keycloak-secret
    # These are simply authorized_callbacks!
    protectedOrigins:
      - origin: https://www.wetsnow.com
---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: keycloak-scope-filter
  namespace: ambassador
spec:
  OAuth2:
    authorizationURL: https://login.wetsnow.com/auth/realms/wetsnow
    clientID: default.wetsnow.com
    secretName: default-keycloak-secret
    # These are simply authorized_callbacks!
    protectedOrigins:
      - origin: https://scope.wetsnow.com
      - origin: https://weave-scope.wetsnow.com
