apiVersion: apps/v1
kind: Deployment
metadata:
  name: pronestheus
  labels:
{{- include "default.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pronestheus
  template:
    metadata:
      labels:
        app: pronestheus
    spec:
      serviceAccountName: pronestheus-service-account
      containers:
        - name: pronestheus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: PRONESTHEUS_NEST_REFRESH_TOKEN
              value: {{ .Values.nest.refresh_token |quote }}
            - name: PRONESTHEUS_NEST_CLIENT_ID
              value: {{ .Values.nest.client_id |quote }}
            - name: PRONESTHEUS_NEST_CLIENT_SECRET
              value: {{ .Values.nest.client_secret |quote }}
            - name: PRONESTHEUS_NEST_PROJECT_ID
              value: {{ .Values.nest.project_id |quote }}
            - name: PRONESTHEUS_OWM_AUTH
              value: {{ .Values.openWeatherMap.token |quote }}
            - name: PRONESTHEUS_OWM_LOCATION
              value: {{ .Values.openWeatherMap.location |quote }}
            - name: PRONESTHEUS_OWM_URL
              value: {{ .Values.openWeatherMap.url |quote }}
          args:
            - "--listen-addr"
            - "0.0.0.0:{{ .Values.service.port }}"
          ports:
            - name: metrics
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
