# this needs prometheus installed for custom resource definition
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quote-server-http-monitor
  namespace: ${namespace}
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      service: quote-server-http
  endpoints:
    - port: http
