---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vector-monitor
  namespace: vector
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: vector-agent
  podMetricsEndpoints:
    - port: metrics
