apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: calendar
  namespace: ${namespace}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "7777"
    prometheus.io/path: "/metrics"
spec:
  calendar:
    example-with-interval:
      # creates an event every 10 seconds
      interval: 20s