# https://github.com/bitnami/charts/tree/master/bitnami/kafka

# any environment variable beginning with KAFKA_CFG_ will be mapped to its corresponding Kafka key.
extraEnvVars:
  - name: KAFKA_CFG_COMPRESSION_TYPE
    value: "gzip"

replicaCount: ${replicaCount}

resources:
  limits:
    cpu: 200m
    memory: 1.0Gi
  requests:
    cpu: 200m
    memory: 1.0Gi

livenessProbe:
  initialDelaySeconds: 300 # java is slow to startup, but this should be a startupProbe

metrics:
  kafka:
    enabled: true
  serviceMonitor:
    enabled: ${promEnabled}
    namespace: monitoring
  jmx:
    enabled: true
  resources:
    limits:
      cpu: 5m
      memory: 64Mi
    requests:
      cpu: 5m
      memory: 64Mi

rbac:
  create: true

persistence:
  enabled: true
  size: 8Gi

service:
  type: ClusterIP

pdb:
  create: true
  ## Min number of pods that must still be available after the eviction
  ##
  #   minAvailable: 1
  ## Max number of pods that can be unavailable after the eviction
  ##
  maxUnavailable: 1

provisioning:
  enabled: false

zookeeper:
  enabled: true
