# https://github.com/kyverno/kyverno/tree/main/charts/kyverno
namespace: ${namespace}
extraArgs:
  - "--v=2"

image:
  # https://github.com/kyverno/kyverno/issues/1764
  tag: v1.3.6-rc1

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 30m
    memory: 50Mi