# Send only to Lightstep

datadog:
  # api_key: ${lightstepAccessToken}
  api_key: ${datadogApiKey}
  dd_url: "https://metricingest.lightstep.com"
  logLevel: INFO

  processAgent:
    enabled: false
