controller:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
  metricsConfig:
    enabled: true

  image:
    tag: ${argo_version}

executor:
  image:
    tag: ${argo_version}

server:
  extraArgs:
    - --auth-mode=server
  image:
    tag: ${argo_version}
