force_change: 2
image:
  repository: mrwetsnow/pronestheus
  tag: ${appVersion}

# Based on NodeExporter Helm chart (https://github.com/helm/charts/blob/master/stable/prometheus-node-exporter/values.yaml)
service:
  type: ClusterIP
  port: 9999
  targetPort: 9999
  nodePort:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port:  "9999"

honeywell:
  refresh_token: ${honeywellRefreshToken}
  client_id: ${honeywellClientID}
  client_secret: ${honeywellClientSecret}
  location_id: ${honeywellLocationID}

nest:
  refresh_token: ${nestRefreshToken}
  client_id: ${nestClientID}
  client_secret: ${nestClientSecret}
  project_id: ${nestProjectID}
  url: https://developer-api.nest.com/devices/thermostats

openWeatherMap:
  token: ${openWeatherToken}
  url: http://api.openweathermap.org/data/2.5/weather
  location: "5128581" # That's Staten Island