# Send only to Lightstep

# https://github.com/DataDog/helm-charts

datadog:
  apiKey: ${lightstepAccessToken}
  # apiKey: ${datadogApiKey}
  dd_url: "https://metricingest.lightstep.com"
  logLevel: INFO

  processAgent:
    enabled: false

  logs:
    enabled: false
    containerCollectAll: false

  dogstatsd:
    useHostPort: true

  kubelet:
    tlsVerify: ${gke}

  env:
    - name: DD_TAGS
      value: cluster_name:${clusterName}

clusterAgent:
  resources:
  requests:
    cpu: 20m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
  env:
    - name: DD_CLUSTER_CHECKS_EXTRA_TAGS
      value: cluster_name:${clusterName}

agents:
  # for kind cluster
  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
      operator: "Exists"

containers:
  agent:
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  processAgent:
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  traceAgent:
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  systemProbe:
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  securityAgent:
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
kube-state-metrics:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
