controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  image:
    tag: ${argo_version}

dashboard:
<<<<<<< HEAD
  enabled: true
=======
  enabled: true
  image:
    tag: ${argo_version}
>>>>>>> c94b983bdfeae72f06fcdac35c3378de784ab385
