controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false # using podAnnotations below

  image:
    tag: ${argo_version}

dashboard:
  enabled: true
  image:
    tag: ${argo_version}

podAnnotations:
  prometheus.io/scrape = "true"
  prometheus.io/port   = 8090
  prometheus.io/path   = "/metrics"
