# https://github.com/datawire/ambassador/tree/master/charts/ambassador
nameOverride: "${name}"

licenseKey:
  value: ${licenseKey}
  annotations: {}
  createSecret: true
metrics:
  serviceMonitor:
    # we use our own
    enabled: false

image:
  repository: docker.io/datawire/aes
  tag: ${app_version}
  pullPolicy: IfNotPresent

replicaCount: 1

podLabels:
  # match the span service.name
  service.name: "ambassador-ambassador"
  service.version: ${app_version}

volumes:
  - name: lightstep-secret-volume
    secret:
      secretName: lightstep-access-token

volumeMounts:
  - name: lightstep-secret-volume
    mountPath: /etc/lightstep-access-token

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 256Mi
adminService:
  annotations: {}
  create: true
  port: 8877
  type: NodePort
service:
  annotations:
    # kubernetes.io/ingress.global-static-ip-name: "ambassador"
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "${backendConfig}"}'
    cloud.google.com/app-protocols: '{"grpc": "HTTP2"}'
  externalIPs: []
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 8443
      targetPort: 8443
    # - name: minecraft
    #   port: 25565
    #   targetPort: 25565
  # type: LoadBalancer
  type: NodePort
  # This breaks on GKE, perhaps healthCheckNodePort is needed?
  # externalTrafficPolicy: Cluster
  # externalTrafficPolicy: Local
env:
  AMBASSADOR_LEGACY_MODE: false
  # https://docs.datadoghq.com/integrations/ambassador/
  STATSD_ENABLED: true
  DOGSTATSD: true
  # STATSD_HOST: "localhost"

envRaw:
  - name: STATSD_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

redis:
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 128Mi

agent:
  enabled: false

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 6
  failureThreshold: 6

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 6
  failureThreshold: 6
