serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: "${serviceAccount}@${projectID}.iam.gserviceaccount.com"
  name: ${serviceAccount}


image:
  repository: ghcr.io/external-secrets/kubernetes-external-secrets
  tag: ${appVersion}

# Free tier (Monthly free usage limits)
# Active secret versions	6 versions
# Access operations	10,000 operations (~13 / hour; 1 every ~4 min)
# Rotation Notifications	3 rotations
env:
  LOG_LEVEL: info
  LOG_MESSAGE_KEY: "msg"
  USE_HUMAN_READABLE_LOG_LEVELS: true
  POLLER_INTERVAL_MILLISECONDS: 600000  # every 600 seconds

#resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

serviceMonitor:
  enabled: false
  interval: "30s"
  namespace: monitoring


podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: 3001
  prometheus.io/path: "/metrics"
