# https://github.com/bitnami/charts/tree/master/bitnami/kube-prometheus
# fullnameOverride: prometheus0
operator:
  service:
    type: ClusterIP
    port: 8080
    clusterIP: None
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  image:
    tag: ${operator_version}
prometheus:
  retention: 7d
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 256Mi
  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
      operator: "Exists"
  service:
    type: ClusterIP
    port: 9090
    clusterIP: None
  persistence:
    enabled: true
    size: 8G
  volumes:
    - name: lightstep-config-volume
      secret:
        secretName: lightstep-config
  containers:
    - name: otel-sidecar
      image: lightstep/opentelemetry-prometheus-sidecar
      imagePullPolicy: Always
      env:
        - name: LIGHTSTEP_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: lightstep-access-token
              key: api-key
              optional: false
      args:
        - --config-file=/etc/lightstep/config.yaml
        - --destination.header="lightstep-access-token=$${LIGHTSTEP_ACCESS_TOKEN}"
      volumeMounts:
        - name: prometheus-prom0-kube-prometheus-prometheus-db
          mountPath: /prometheus
          subPath: prometheus-db
        - name: lightstep-config-volume
          mountPath: /etc/lightstep
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 128Mi
alertmanager:
  enabled: false
exporters:
  kube-state-metrics:
    enabled: false
  node-exporter:
    enabled: false
kube-state-metrics:
  serviceMonitor:
    enabled: false
node-exporter:
  serviceMonitor:
    enabled: false
    jobLabel: jobLabel
    relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
          - __meta_kubernetes_pod_node_name
        targetLabel: kubernetes_node
  extraArgs:
    collector.filesystem.ignored-mount-points: "^/(dev|proc|sys|var/lib/docker/.+)($|/)"
    collector.filesystem.ignored-fs-types: "^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$"
    collector.systemd:
    collector.processes:
kubelet:
  enabled: false
  namespace: kube-system
  serviceMonitor:
    metricRelabelings:
      - action: replace
        sourceLabels:
          - node
        targetLabel: instance
coreDns:
  enabled: false
  service:
    enabled: false
kubeControllerManager:
  enabled: false
  service:
    enabled: false
  serviceMonitor:
    https: true
    insecureSkipVerify: true
kubeScheduler:
  enabled: false
  service:
    enabled: false
    port: 10259
    targetPort: 10259
  serviceMonitor:
    https: true
    insecureSkipVerify: true
kubeApiServer:
  enabled: false
kubeProxy:
  enabled: false
